export const atlasTheme = {
  dark: {
    sidebarBg: "bg-[#0b0f18]/95",
    sidebarBorder: "border-amber-900/20",
    sidebarSubBorder: "border-amber-900/10",
    headerText: "text-amber-200/70",
    centuryText: "text-amber-200/90",
    centuryHover: "group-hover:text-amber-200",
    chevron: "text-amber-500/70",
    periodActive: "text-amber-300",
    periodInactive: "text-gray-400",
    periodHover: "group-hover:text-amber-300/80",
    buttonBg: "bg-[#0b0f18]/90",
    buttonBorder: "border-amber-900/30",
    buttonText: "text-amber-300",
    buttonHoverText: "hover:text-amber-200",
    buttonHoverBg: "hover:bg-[#141c2c]/90",
    mapBg: "#06080d",
    tileUrl:
      "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_Black_Marble/default/2016-01-01/GoogleMapsCompatible_Level8/{z}/{y}/{x}.png",
    tileAttribution: "&copy; NASA Black Marble",
    labelTileUrl:
      "https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}",
    labelColor: "#ffffff",
    labelShadow: "0 0 6px rgba(0,0,0,0.9),0 0 12px rgba(0,0,0,0.6)",
    hoverFill: "#fbbf24",
    hoverOpacity: 0.18,
  },
  light: {
    sidebarBg: "bg-[#faf5eb]/95",
    sidebarBorder: "border-amber-700/25",
    sidebarSubBorder: "border-amber-700/15",
    headerText: "text-amber-800/70",
    centuryText: "text-amber-900/90",
    centuryHover: "group-hover:text-amber-800",
    chevron: "text-amber-600/70",
    periodActive: "text-amber-700",
    periodInactive: "text-amber-900/50",
    periodHover: "group-hover:text-amber-700/80",
    buttonBg: "bg-[#faf5eb]/90",
    buttonBorder: "border-amber-700/30",
    buttonText: "text-amber-800",
    buttonHoverText: "hover:text-amber-700",
    buttonHoverBg: "hover:bg-[#f0e8d8]/90",
    mapBg: "#a8c8e8",
    tileUrl:
      "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_NextGeneration/default/2004-06-01/GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpeg",
    tileAttribution: "&copy; NASA Blue Marble",
    labelTileUrl:
      "https://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}",
    labelColor: "#1a1a2e",
    labelShadow: "0 0 4px rgba(255,255,255,0.9),0 0 8px rgba(255,255,255,0.7)",
    hoverFill: "#c8851a",
    hoverOpacity: 0.3,
  },
};