export const LABELS = [
  // Continenti
  { name: "Europa", lat: 54, lng: -15, type: "continent" },
  { name: "Asia", lat: 45, lng: 75, type: "continent" },
  { name: "Africa", lat: 5, lng: 10, type: "continent" },
  { name: "America del Nord", lat: 48, lng: -125, type: "continent" },
  { name: "America del Sud", lat: -15, lng: -82, type: "continent" },
  { name: "Oceania", lat: -25, lng: 118, type: "continent" },
  { name: "Antartide", lat: -78, lng: -10, type: "continent" },

  // Europa
  { name: "Italia", lat: 42.5, lng: 12.5, type: "country" },
  { name: "Francia", lat: 46.6, lng: 2.5, type: "country" },
  { name: "Spagna", lat: 40, lng: -3.7, type: "country" },
  { name: "Portogallo", lat: 39.6, lng: -8, type: "country" },
  { name: "Germania", lat: 51.1, lng: 10.4, type: "country" },
  { name: "Regno Unito", lat: 54, lng: -2, type: "country" },
  { name: "Irlanda", lat: 53.5, lng: -8, type: "country" },
  { name: "Paesi Bassi", lat: 52.3, lng: 5.3, type: "country" },
  { name: "Belgio", lat: 50.8, lng: 4.5, type: "country" },
  { name: "Svizzera", lat: 46.8, lng: 8.2, type: "country" },
  { name: "Austria", lat: 47.5, lng: 14.5, type: "country" },
  { name: "Polonia", lat: 52, lng: 19.5, type: "country" },
  { name: "Ucraina", lat: 49, lng: 32, type: "country" },
  { name: "Russia", lat: 62, lng: 95, type: "country" },
  { name: "Turchia", lat: 39, lng: 35, type: "country" },
  { name: "Grecia", lat: 39, lng: 22, type: "country" },
  { name: "Romania", lat: 46, lng: 25, type: "country" },
  { name: "Ungheria", lat: 47.2, lng: 19.5, type: "country" },
  { name: "Rep. Ceca", lat: 49.8, lng: 15.5, type: "country" },
  { name: "Svezia", lat: 62, lng: 15, type: "country" },
  { name: "Norvegia", lat: 65, lng: 13, type: "country" },
  { name: "Finlandia", lat: 64, lng: 26, type: "country" },
  { name: "Danimarca", lat: 56, lng: 10, type: "country" },
  { name: "Islanda", lat: 65, lng: -18, type: "country" },
  { name: "Serbia", lat: 44.2, lng: 20.9, type: "country" },
  { name: "Croazia", lat: 45.2, lng: 15.5, type: "country" },
  { name: "Bulgaria", lat: 42.7, lng: 25.5, type: "country" },
  { name: "Slovacchia", lat: 48.7, lng: 19.7, type: "country" },
  { name: "Bielorussia", lat: 53.5, lng: 28, type: "country" },
  { name: "Lituania", lat: 55.2, lng: 24, type: "country" },
  { name: "Lettonia", lat: 57, lng: 24.5, type: "country" },
  { name: "Estonia", lat: 59, lng: 25.5, type: "country" },
  { name: "Moldavia", lat: 47, lng: 28.8, type: "country" },
  { name: "Albania", lat: 41, lng: 20, type: "country" },

  // Americhe
  { name: "Stati Uniti", lat: 39, lng: -98, type: "country" },
  { name: "Canada", lat: 56, lng: -96, type: "country" },
  { name: "Messico", lat: 23, lng: -102, type: "country" },
  { name: "Brasile", lat: -10, lng: -52, type: "country" },
  { name: "Argentina", lat: -35, lng: -65, type: "country" },
  { name: "Cile", lat: -33, lng: -71, type: "country" },
  { name: "Colombia", lat: 4, lng: -73, type: "country" },
  { name: "Venezuela", lat: 8, lng: -66, type: "country" },
  { name: "Perù", lat: -10, lng: -76, type: "country" },
  { name: "Cuba", lat: 22, lng: -79.5, type: "country" },
  { name: "Guatemala", lat: 15.5, lng: -90, type: "country" },
  { name: "Bolivia", lat: -17, lng: -65, type: "country" },
  { name: "Ecuador", lat: -1.5, lng: -78.5, type: "country" },
  { name: "Paraguay", lat: -23, lng: -58, type: "country" },
  { name: "Uruguay", lat: -33, lng: -56, type: "country" },

  // Asia
  { name: "Cina", lat: 35, lng: 103, type: "country" },
  { name: "Giappone", lat: 36, lng: 138, type: "country" },
  { name: "India", lat: 22, lng: 79, type: "country" },
  { name: "Corea del Sud", lat: 36, lng: 128, type: "country" },
  { name: "Corea del Nord", lat: 40, lng: 127, type: "country" },
  { name: "Indonesia", lat: -2, lng: 118, type: "country" },
  { name: "Filippine", lat: 12, lng: 122, type: "country" },
  { name: "Vietnam", lat: 16, lng: 107, type: "country" },
  { name: "Thailandia", lat: 15, lng: 101, type: "country" },
  { name: "Myanmar", lat: 20, lng: 97, type: "country" },
  { name: "Malesia", lat: 3, lng: 109, type: "country" },
  { name: "Mongolia", lat: 47, lng: 104, type: "country" },
  { name: "Pakistan", lat: 30, lng: 69, type: "country" },
  { name: "Afghanistan", lat: 34, lng: 67, type: "country" },
  { name: "Iran", lat: 33, lng: 53, type: "country" },
  { name: "Iraq", lat: 33, lng: 44, type: "country" },
  { name: "Arabia Saudita", lat: 24, lng: 45, type: "country" },
  { name: "Kazakistan", lat: 48, lng: 67, type: "country" },
  { name: "Uzbekistan", lat: 41.5, lng: 64, type: "country" },
  { name: "Siria", lat: 35, lng: 38, type: "country" },
  { name: "Giordania", lat: 31, lng: 36.5, type: "country" },
  { name: "Israele", lat: 31.5, lng: 35, type: "country" },
  { name: "Emirati Arabi", lat: 24, lng: 54, type: "country" },
  { name: "Bangladesh", lat: 24, lng: 90, type: "country" },
  { name: "Sri Lanka", lat: 7.5, lng: 81, type: "country" },
  { name: "Nepal", lat: 28.2, lng: 84.2, type: "country" },
  { name: "Cambogia", lat: 12.5, lng: 105, type: "country" },

  // Africa
  { name: "Egitto", lat: 26, lng: 30, type: "country" },
  { name: "Sudafrica", lat: -30, lng: 25, type: "country" },
  { name: "Nigeria", lat: 9.5, lng: 8, type: "country" },
  { name: "Marocco", lat: 32, lng: -6, type: "country" },
  { name: "Algeria", lat: 28, lng: 3, type: "country" },
  { name: "Kenya", lat: 0, lng: 38, type: "country" },
  { name: "Etiopia", lat: 9, lng: 39, type: "country" },
  { name: "Tanzania", lat: -6, lng: 35, type: "country" },
  { name: "Rep. Dem. del Congo", lat: -3, lng: 23, type: "country" },
  { name: "Sudan", lat: 16, lng: 30, type: "country" },
  { name: "Libia", lat: 27, lng: 17, type: "country" },
  { name: "Tunisia", lat: 34, lng: 9, type: "country" },
  { name: "Ghana", lat: 7.5, lng: -1.5, type: "country" },
  { name: "Angola", lat: -12, lng: 18, type: "country" },
  { name: "Mozambico", lat: -17, lng: 35, type: "country" },
  { name: "Madagascar", lat: -19, lng: 47, type: "country" },
  { name: "Senegal", lat: 14.5, lng: -14.5, type: "country" },
  { name: "Mali", lat: 17, lng: -2, type: "country" },
  { name: "Niger", lat: 17, lng: 9.5, type: "country" },
  { name: "Ciad", lat: 15, lng: 19, type: "country" },
  { name: "Somalia", lat: 5, lng: 46, type: "country" },
  { name: "Camerun", lat: 6, lng: 12, type: "country" },

  // Oceania
  { name: "Australia", lat: -25, lng: 134, type: "country" },
  { name: "Nuova Zelanda", lat: -42, lng: 174, type: "country" },
  { name: "Papua Nuova Guinea", lat: -6, lng: 147, type: "country" },


];