// Traduzioni italiane dei nomi storici di stati, imperi e territori usati dai
// GeoJSON di confini storici (historical-basemaps). Sostituisce la vecchia
// traduzione a runtime via LLM: qui il set di nomi è finito e noto.
//
// Regola: sono elencate SOLO le voci la cui forma italiana differisce
// dall'originale. Per tutti gli altri nomi (paesi identici in italiano, popoli
// indigeni senza esonimo, ecc.) il chiamante usa il nome originale come
// fallback. Estendibile a mano quando si aggiungono nuovi periodi/mappe.

export const TERRITORY_NAMES_IT = {
  // Europa – stati e regioni
  "Italy": "Italia",
  "France": "Francia",
  "Spain": "Spagna",
  "Portugal": "Portogallo",
  "Germany": "Germania",
  "Greece": "Grecia",
  "Switzerland": "Svizzera",
  "Swiss Confederation": "Confederazione Svizzera",
  "Netherlands": "Paesi Bassi",
  "Belgium": "Belgio",
  "Luxembourg": "Lussemburgo",
  "Denmark": "Danimarca",
  "Denmark-Norway": "Danimarca-Norvegia",
  "Sweden": "Svezia",
  "Sweden–Norway": "Svezia-Norvegia",
  "Iceland": "Islanda",
  "Greenland": "Groenlandia",
  "Scottalnd": "Scozia",
  "England and Ireland": "Inghilterra e Irlanda",
  "United Kingdom": "Regno Unito",
  "United Kingdom of Great Britain and Ireland": "Regno Unito di Gran Bretagna e Irlanda",
  "Holy Roman Empire": "Sacro Romano Impero",
  "Austrian Empire": "Impero Austriaco",
  "Austria Hungary": "Austria-Ungheria",
  "Prussia": "Prussia",
  "Bavaria": "Baviera",
  "Saxony": "Sassonia",
  "Thuringia": "Turingia",
  "Hanover": "Hannover",
  "Bremen": "Brema",
  "Hamburg": "Amburgo",
  "Lübeck": "Lubecca",
  "Palatinate": "Palatinato",
  "Electoral Hesse": "Assia Elettorale",
  "Grand Duchy of Hesse": "Granducato d'Assia",
  "Bosnia-Herzegovina": "Bosnia-Erzegovina",
  "Papal States": "Stato Pontificio",
  "Kingdom of Sardinia": "Regno di Sardegna",
  "Kingdom of the Two Sicilies": "Regno delle Due Sicilie",
  "Sardinia": "Sardegna",
  "Sardinia-Piedmont": "Sardegna-Piemonte",
  "Sicily": "Sicilia",
  "Naples": "Napoli",
  "Milan": "Milano",
  "Venice": "Venezia",
  "Venetia": "Veneto",
  "Genoa": "Genova",
  "Lombardy": "Lombardia",
  "Tuscany": "Toscana",
  "Geneva": "Ginevra",
  "Franche-Comté": "Franca Contea",
  "Republic of Kraków": "Repubblica di Cracovia",
  "Polish–Lithuanian Commonwealth": "Confederazione Polacco-Lituana",
  "Tsardom of Muscovy": "Zarato di Moscovia",
  "Russian Empire": "Impero Russo",
  "Nogai Horde": "Orda Nogai",

  // Vicino Oriente e Asia centrale
  "Ottoman Empire": "Impero Ottomano",
  "Safavid Empire": "Impero Safavide",
  "Persia": "Persia",
  "Cyrenaica": "Cirenaica",
  "Bokhara Khanate": "Khanato di Bukhara",
  "Khiva Khanate": "Khanato di Khiva",
  "Quazaq Khanate": "Khanato Kazako",
  "central Asian khanates": "Khanati dell'Asia centrale",
  "Trucial Oman": "Oman della Tregua",

  // Asia orientale e meridionale
  "Mughal Empire": "Impero Moghul",
  "Manchu Empire": "Impero Manciù",
  "Maratha Confederacy": "Confederazione Maratha",
  "British Raj": "Raj Britannico",
  "British East India Company": "Compagnia Britannica delle Indie Orientali",
  "Hindu Kingdoms": "Regni Indù",
  "Korea": "Corea",
  "Japan": "Giappone",
  "Imperial Japan": "Giappone Imperiale",
  "Tokugawa Shogunate": "Shogunato Tokugawa",
  "Post-Ming Warlords": "Signori della guerra post-Ming",
  "Cambodia": "Cambogia",
  "Burma": "Birmania",
  "Cochin China": "Cocincina",
  "French Indochina": "Indocina Francese",
  "Laotian states": "Stati laotiani",
  "Shan states": "Stati Shan",
  "Rattanakosin Kingdom": "Regno di Rattanakosin",
  "Middag Kingdom": "Regno di Middag",
  "Philippines": "Filippine",
  "Netherlands Indies": "Indie Olandesi",
  "Dutch East Indies": "Indie Orientali Olandesi",
  "Dutch Formosa": "Formosa Olandese",
  "Kuril Islands": "Isole Curili",

  // Africa
  "Egypt": "Egitto",
  "Morocco": "Marocco",
  "Ethiopia": "Etiopia",
  "Ivory Coast": "Costa d'Avorio",
  "Gold Coast (GB)": "Costa d'Oro (GB)",
  "Cape Colony": "Colonia del Capo",
  "Orange Free State": "Stato Libero dell'Orange",
  "Fulani Empire": "Impero Fulani",
  "Sokoto Caliphate": "Califfato di Sokoto",
  "Tukular Caliphate": "Califfato Tukulor",
  "Kong Empire": "Impero di Kong",
  "First Samori Empire": "Primo Impero di Samori",
  "Second Samori Empire": "Secondo Impero di Samori",
  "Wassoulou Empire": "Impero del Wassoulou",
  "Wadai Empire": "Impero del Wadai",
  "Mossi States": "Stati Mossi",
  "Hausa States": "Stati Hausa",
  "Borgu States": "Stati di Borgu",
  "Dendi Kingdom": "Regno Dendi",
  "Sultanate of Damagaram": "Sultanato di Damagaram",
  "Sultanate of Utetera": "Sultanato di Utetera",
  "Sultinate of Zanzibar": "Sultanato di Zanzibar",
  "Expansionist Kingdom of Merina": "Regno espansionista di Merina",
  "Portuguese East Africa": "Africa Orientale Portoghese",
  "Portuguese Guinea": "Guinea Portoghese",
  "Spanish Guinea": "Guinea Spagnola",
  "Tunis": "Tunisi",
  "Algiers": "Algeri",

  // Americhe
  "United States": "Stati Uniti",
  "United States of America": "Stati Uniti d'America",
  "New France": "Nuova Francia",
  "New Amsterdam": "Nuova Amsterdam",
  "Mexico": "Messico",
  "Peru": "Perù",
  "Chile": "Cile",
  "British Guiana": "Guiana Britannica",
  "Dutch Guiana": "Guiana Olandese",
  "French Guiana": "Guiana Francese",
  "Kingdom of Brazil": "Regno del Brasile",
  "Dutch Brazil": "Brasile Olandese",
  "Portuguese Brazil": "Brasile Portoghese",
  "Viceroyalty of Brazil": "Vicereame del Brasile",
  "Vice Royalty of Peru": "Vicereame del Perù",
  "Vice-Royalty of Peru": "Vicereame del Perù",
  "Vice-Royalty of New Granada": "Vicereame della Nuova Granada",
  "Vice-Royalty of New Spain": "Vicereame della Nuova Spagna",
  "United Provinces of La Plata": "Province Unite del Río de la Plata",
  "Dominican Republic": "Repubblica Dominicana",
  "Antigua and Barbuda": "Antigua e Barbuda",
  "Guadeloupe": "Guadalupa",
  "Martinique": "Martinica",

  // Oceania
  "Kingdom of Hawaii": "Regno delle Hawaii",
  "Kongldom of Hawaii": "Regno delle Hawaii",
  "New South Wales": "Nuovo Galles del Sud",
  "New South Wales (UK)": "Nuovo Galles del Sud (UK)",
  "Northern Territory (UK)": "Territorio del Nord (UK)",
  "South Australia (UK)": "Australia Meridionale (UK)",
  "Western Australia (UK)": "Australia Occidentale (UK)",
  "Fiji": "Figi",
};
